/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jin_jnidemo_demo2_JNIExample */

#ifndef _Included_com_jin_jnidemo_demo2_JNIExample
#define _Included_com_jin_jnidemo_demo2_JNIExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jin_jnidemo_demo2_JNIExample
 * Method:    nativeMethod
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jin_jnidemo_demo2_JNIExample_nativeMethod
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
