/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jin_jnidemo_demo_NativeCrashHandler */

#ifndef _Included_com_jin_jnidemo_demo_NativeCrashHandler
#define _Included_com_jin_jnidemo_demo_NativeCrashHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jin_jnidemo_demo_NativeCrashHandler
 * Method:    registerSignalHandlers
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jin_jnidemo_demo_NativeCrashHandler_registerSignalHandlers
  (JNIEnv *, jclass);

/*
 * Class:     com_jin_jnidemo_demo_NativeCrashHandler
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jin_jnidemo_demo_NativeCrashHandler_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
